# Theme translate.
#
# Require: - RainLab:Translate
# Example:
#   en:
#     site.name: 'Bootstrap'
# Use:
#   {{ 'site.name'|_ }}
########################################################################################################################